package uk.ac.masts.sifids.entities;

import android.arch.persistence.room.Entity;
import android.arch.persistence.room.Ignore;
import android.arch.persistence.room.PrimaryKey;

import java.util.ArrayList;
import java.util.List;

@Entity(tableName = "port")
public class Port extends EntityWithId {

    private static final String[] PORTS = {
            "Aberdeen",
            "Achiltibuie",
            "Aith",
            "Alloa",
            "Annan",
            "Anstruther",
            "Applecross",
            "Arbroath",
            "Ardentinny",
            "Ardnamurchan",
            "Ardrishaig",
            "Ardrossan",
            "Ardyne",
            "Arisaig",
            "Arran",
            "Auckengill",
            "Aultbea",
            "Avoch",
            "Ayr",
            "Back",
            "Balintore",
            "Ballantrae",
            "Baltasound",
            "Balvicar",
            "Banff",
            "Barcaldine",
            "Barra",
            "Benbecula",
            "Bernera (Lewis)",
            "Berneray (N Uist)",
            "Birsay",
            "Boddam",
            "Bowmore",
            "Bracadale",
            "Breasclete",
            "Broadford",
            "Brodick",
            "Brora",
            "Brough",
            "Bruichladdich",
            "Buckie",
            "Bunessan",
            "Burghead",
            "Burnmouth",
            "Burntisland",
            "Burra (Hamnavoe)",
            "Burravoe",
            "Burray",
            "Bute",
            "Cairnbulg",
            "Campbeltown",
            "Canna (Outer Isles)",
            "Carbost",
            "Carloway",
            "Carradale",
            "Carron",
            "Carsethorn",
            "Castlebay",
            "Castletown",
            "Catterline",
            "Central Mainland",
            "Coll",
            "Collafirth",
            "Collieston",
            "Colonsay",
            "Corpach",
            "Corran",
            "Coulport",
            "Cove",
            "Craighouse",
            "Crail",
            "Crinan",
            "Cromarty",
            "Crosskirk",
            "Cuan",
            "Culkein/Drumbeg",
            "Cullivoe",
            "Cumbraes",
            "Deerness",
            "Dingwall",
            "Dornoch",
            "Drummore",
            "Dumfries",
            "Dunbar",
            "Dunbeath",
            "Dundee",
            "Dunoon",
            "Dunure",
            "Dunvegan",
            "Dysart",
            "Eday",
            "Eisken",
            "Elie",
            "Eriboll",
            "Eshaness",
            "Eyemouth",
            "Fairisle",
            "Findochty",
            "Fionnphort",
            "Fisherrow",
            "Foindlemore - Loch Glendhu",
            "Fort William",
            "Fortrose",
            "Fraserburgh",
            "Furnace",
            "Gairloch",
            "Gardenstown",
            "Gareloch",
            "Garlieston",
            "Garrabost",
            "Gigha",
            "Girvan",
            "Glasgow",
            "Glenuig",
            "Golspie",
            "Gourdon",
            "Gourock",
            "Grangemouth",
            "Granton",
            "Greenock",
            "Grimsay",
            "Helensburgh",
            "Helmsdale",
            "Holm",
            "Hopeman",
            "Hougharry and Loch Eport",
            "Hoy",
            "Inverallochy",
            "Inveraray",
            "Invergordon",
            "Inverkip",
            "Inverness",
            "Irvine",
            "Islay",
            "ISLE of Whithorn",
            "John O'Groats",
            "Johnshaven",
            "Jura",
            "Kallin",
            "Keiss",
            "Kilchoan",
            "Kincardine",
            "Kinghorn",
            "Kinlochbervie",
            "Kinlochleven",
            "Kippford",
            "Kirkcaldy",
            "Kirkcudbright",
            "Kirkwall",
            "Kirtomy",
            "Kyle",
            "Kyles Of Bute",
            "Kylesku",
            "Largs",
            "Latheronwheel",
            "Leith",
            "Lerwick",
            "Levenwick",
            "Leverburgh",
            "Little Loch Broom",
            "Loch Buie (Mull)",
            "Loch Carnan",
            "Loch Long",
            "Loch Scridain (Mull)",
            "Lochboisdale",
            "Lochinver",
            "Lochmaddy",
            "Lochs",
            "Lossiemouth",
            "Luing",
            "Lybster",
            "Macduff",
            "Machrihanish",
            "Maidens",
            "Mallaig",
            "Meikle Ferry",
            "Methil & Leven",
            "Mid Yell",
            "Montrose",
            "Muasdale",
            "Nairn",
            "Ness",
            "Newhaven (Scotland)",
            "Newport on Tay",
            "North Berwick",
            "North Harris",
            "North Lochs",
            "North Queensferry",
            "North Roe to Hillswick",
            "North Uist",
            "Northbay",
            "Northmavine",
            "Oban",
            "Out Skerries",
            "Pennan",
            "Peterhead",
            "Pettycur",
            "Pittenweem",
            "Poolewe - Cove",
            "Port Appin",
            "Port Askaig",
            "Port Ellen",
            "Port Errol",
            "Port Seton",
            "Port William",
            "Portincaple",
            "Portknockie",
            "Portmahomack",
            "Portnaguran & Ness",
            "Portnahaven",
            "Portnalong",
            "Portpatrick",
            "Portree",
            "Portskerra",
            "Portsoy",
            "Rosehearty",
            "Rosemarkie",
            "Rothesay",
            "Rousay",
            "Rudh Re - Red Point",
            "S Mainland & Fair Isle",
            "S Ronaldsay",
            "Salen",
            "Saltcoats",
            "Sanday",
            "Sandhaven & Pitullie",
            "Sandwick",
            "Scalloway",
            "Scalpay",
            "Scarfskerry",
            "Scourie",
            "Scrabster",
            "Shieldaig",
            "Skeld",
            "Skerray",
            "Skerries",
            "Sleat",
            "Snizort",
            "South Harris",
            "South Lochs",
            "South Uist & Eriskay",
            "Southend",
            "St Abbs",
            "St Andrews",
            "St Combs and Charleston",
            "St Monans",
            "Staxigoe",
            "Stockinish",
            "Stonehaven",
            "Stornoway",
            "Stranraer",
            "Strathaird",
            "Stroma",
            "Stromness",
            "Stronsay",
            "Sullom / Toft",
            "Symbister",
            "Talmine",
            "Tarbert",
            "Tayinloan",
            "Tayport",
            "Tayvallich",
            "Thurso",
            "Tingwall",
            "Tiree",
            "Tobermory (Mull)",
            "Toberonochy",
            "Torridon",
            "Troon",
            "Uig",
            "Ullapool",
            "Ulva Ferry",
            "Uyeasound",
            "Vidlin",
            "Voe",
            "Walls",
            "Walls (Orkney)",
            "Wemyss Bay",
            "West Burrafirth",
            "West Loch Tarbert",
            "West Mainland",
            "West Wemyss",
            "Westray",
            "Whaligoe",
            "Whalsay",
            "Whinnyfold",
            "Whitehills",
            "Wick",
            "Wigtown",
            "Yell, Fetlar & Unst"
    };

    public String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public static List<Port> createPorts() {
        List<Port> portObjects = new ArrayList();
        for(String portName : PORTS) {
            Port port = new Port();
            port.setName(portName);
            portObjects.add(port);
        }
        return portObjects;
    }

    public String toString() {
        return this.getName();
    }
}
